
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Orkidea.Pioneer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ActivityLog
{

    public int id { get; set; }

    public int idUsuario { get; set; }

    public System.DateTime fecha { get; set; }

    public string accion { get; set; }

}

}
