
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Orkidea.Pioneer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Issue
{

    public Issue()
    {

        this.IssueDetail = new HashSet<IssueDetail>();

    }


    public int id { get; set; }

    public int idTaladro { get; set; }

    public string fuente { get; set; }

    public string descripcion { get; set; }

    public string nombreReportador { get; set; }

    public System.DateTime fechaReporte { get; set; }

    public string cargoReportador { get; set; }

    public string empresaReportador { get; set; }

    public string fotoAntes { get; set; }

    public string fotoDespues { get; set; }

    public System.DateTime fechaCreacion { get; set; }

    public int idUsuarioCrea { get; set; }

    public Nullable<System.DateTime> fechaCierre { get; set; }

    public Nullable<int> idUsuarioCierre { get; set; }

    public string comentariosCierre { get; set; }



    public virtual ICollection<IssueDetail> IssueDetail { get; set; }

}

}
