
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Orkidea.Pioneer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class IssueDetail
{

    public int id { get; set; }

    public int idHallazgo { get; set; }

    public string accion { get; set; }

    public string responsable { get; set; }

    public System.DateTime fechaPropuestaCierre { get; set; }

    public int idUsuarioRegistra { get; set; }

    public System.DateTime fechaRegistro { get; set; }



    public virtual Issue Issue { get; set; }

}

}
