
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Orkidea.Pioneer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class IssueDetail
{

    public int id { get; set; }

    public int idHallazgo { get; set; }

    public string accion { get; set; }

    public string responsable { get; set; }

    public System.DateTime fechaPropuestaCierre { get; set; }

    public int idUsuarioRegistra { get; set; }

    public System.DateTime fechaRegistro { get; set; }



    public virtual Issue Issue { get; set; }

}

}
