
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Orkidea.Pioneer.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class NearMiss
{

    public int id { get; set; }

    public System.DateTime fechaApertura { get; set; }

    public int idUsuarioAbre { get; set; }

    public string actividadReporteador { get; set; }

    public string tipoHallazgo { get; set; }

    public int idUbicacion { get; set; }

    public string descripcion { get; set; }

    public string accionSugeida { get; set; }

    public string calidad { get; set; }

    public string salud { get; set; }

    public string asuntosAmbientales { get; set; }

    public string condicionesTrabajo { get; set; }

    public string usoEpp { get; set; }

    public string analisisHallazgo { get; set; }

    public Nullable<int> idUsuarioAnalisis { get; set; }

    public Nullable<System.DateTime> fechaAnalisis { get; set; }

    public Nullable<System.DateTime> fechaCierre { get; set; }

    public Nullable<int> idUsuarioCierra { get; set; }

    public string observacionesCierre { get; set; }

}

}
