//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.Pioneer.DataAccesssEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Orkidea.Pioneer.Entities;
    
    public partial class pioneerEntities : DbContext
    {
        public pioneerEntities()
            : base("name=pioneerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLog { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<NewsPaper> NewsPaper { get; set; }
        public virtual DbSet<ProcessDocument> ProcessDocument { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectDocument> ProjectDocument { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<FileUpload> FileUpload { get; set; }
        public virtual DbSet<mimetype> mimetype { get; set; }
    }
}
